### PR TITLE
Add `stylelint-order`

### LINKED ISSUE #1: Sort properties alphabetically
Lets you find properties easier and think less about grouping them in "logical" order or whatever. We could use https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-alphabetical-order.

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #1 

Instead of sorting alphabetically, which isn't very useful, I decided to sort properties semantically. This will help readability as you can quickly see what properties changes the CSS the most. The general order is: existence, box model, position, float, flexbox/grid/column, transform, visibility, style, interactivity. This is something I've been thinking about for a long time.

Thoughts?

### CODE REVIEW

**Comment by sindresorhus** [comment]
// @kevva @CodeTheory @SamVerschueren @vadimdemedes

**Comment by kevva** [comment]
I used this model before but it's confusing and requires some thought when writing. Having a linter that tells you when it's wrong helps but when reading the code it might be harder to find what you're looking for.

**Comment by sindresorhus** [comment]
It’s autofixable. So autofix on save would make it an afterthought.

**Comment by kevva** [comment]
Yes, writing it is no problem with a linter, but reading it is.

**Comment by SamVerschueren** [comment]
I don't really have any particular thought on this one. To be honest, I never thought about ordering my CSS properties. So whatever comes out of this, it will always be better because it enforces consistency.

**Comment by CodeTheory** [comment]
This actually seems good for me. I often instinctively write CSS in blocks of what the properties do and then when I edit CSS, I add/edit around the properties that do the same sort of thing.

I think this will make scanning and changing CSS easier. 👍

**Comment by sindresorhus** [comment]
Cool. Let's try it out then. Can always change it after some usage.

**Comment by sindresorhus** [comment]
@CodeTheory Let me know if you see any missing CSS properties or something weird about the order ;)

**Comment by bfred-it** [comment]
FYI I hate this so much 😄 

Good thing I can disable it :)

**Comment by sindresorhus** [comment]
@bfred-it Why do you hate it? Have you tried it with auto-fix in the editor?

**Comment by bfred-it** [comment]
1. It doesn't let me group features logically
1b. You can't comment whole "features", e.g.
```css
.a {
   unrelated: property;
   and: more;

  // Prevent bug XXX in browser XX
  opacity: 0.999;
  transform: translateZ(0);
}
```
2. It requires an extra step, impossible if I decide to just push a _one-line fix_ in the browser

**Comment by sindresorhus** [comment]
I'm starting to hate it too. It's just too strict. I really like it in theory, but in practice, it just ends up being annoying. I'll disable it for now and we'll see what to do about it.

**Comment by kevva** [comment]
@bfred-it, you could still achieve that by using the same style as [`normalize.css`](https://github.com/necolas/normalize.css/blob/master/normalize.css#L6-L16), although I'm not a huge fan of that myself.

I still believe alphabetical order is easier to write (and read) while keeping your CSS consistent.

**Pull request merged**
